[PinPadCompartilhado]
Porta=AUTO_USB

[PinPad]
HabilitaTrace=1
MensagemPadrao=NGCH

[CliSiTefI]
HabilitaTrace=1
TraceRotativo=10
TamanhoTraceRotativo=81920
DiretorioTrace=./files

[CliSiTef]
HabilitaTrace=1
TraceRotativo=10
TamanhoTraceRotativo=81920
DiretorioTrace=./files

[SiTef]
MantemConexaoAtiva=1
TempoEsperaConexao=20
TempoEsperaDesfazimento=10
TempoEsperaConfirmacao=10
TempoAdicionalEspera=10

[TabTraducao]
NomeArqTraducao=Mens.txt

[Geral]
transacoesadicionaishabilitadas=7;8;9;14;16;17;26;27;28;123;3003;3020;3289;3240;3021;3022;3919;4179;130;3203;3624;3627;
; 1 = Cheque
TransacoesDesabilitadas=1

[RecargaCelular]
HabilitaRecargaMultiConcessionaria=1
TipoConfirmacaoNumeroCelular=0
